# Generated by Django 4.1.3 on 2022-12-20 00:50

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i_am',
            options={'verbose_name': 'Portrait', 'verbose_name_plural': 'Portraits '},
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('main', 'Principal'), ('about', 'A propos'), ('facts', 'Faits'), ('skills', 'Compétences'), ('resume', 'Curuculum Vitae'), ('portfolio', 'Portfolio'), ('certificats', 'Certificats'), ('testimonials', 'Témoignages'), ('contact', 'Nous Contacter')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bg_wallpaper',
            field=models.ImageField(blank=True, default='bg_wallpaper/default_bg.jpg', null=True, upload_to=cv.models.UserProfile.rename_upload_bg_wallpaper),
        ),
    ]
