# Generated by Django 4.1.3 on 2022-12-25 05:44

import cv.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv', '0002_alter_i_am_options_alter_section_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesportfolio',
            options={'verbose_name': 'Catégorie de Portfolio', 'verbose_name_plural': 'Catégories de Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='screenshotsportfolio',
            options={'verbose_name': 'Capture de Portfolio', 'verbose_name_plural': 'Captures de Portfolios'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='color_display',
            field=models.CharField(choices=[('blue', 'Bleu'), ('orange', 'Orange'), ('pink', 'Rose'), ('yellow', 'Jaune'), ('red', 'Rouge'), ('teal', 'Sarcelle')], max_length=10, verbose_name="Couleur d'affichage"),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='link_to_certificat',
            field=models.URLField(blank=True, null=True, verbose_name='Lien vers le certificat'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='organism',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organisme'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.userprofile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailadress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Objet'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='iconeb',
            field=models.CharField(choices=[('alarm-fill', '<div class="count-box " ><i class="bi bi-alarm-fill"></i></div>'), ('alarm', '<div class="count-box " ><i class="bi bi-alarm"></i></div>')], default=None, max_length=50, null=True, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.userprofile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='i_am',
            name='i_am',
            field=models.CharField(max_length=50, verbose_name='Je suis:'),
        ),
        migrations.AlterField(
            model_name='i_am',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.userprofile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(default='Hors Catégorie', on_delete=django.db.models.deletion.SET_DEFAULT, to='cv.categoriesportfolio', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.userprofile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='category',
            field=models.CharField(choices=[('Parcour Educationnel', 'Edu'), ('Parcour Professionel', 'Pro'), ('Autre Experience', 'Exp')], default='EXP', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='endPeriode',
            field=models.DateField(blank=True, null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.userprofile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='startPeriode',
            field=models.DateField(blank=True, null=True, verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='screenshotsportfolio',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.portfolio', verbose_name='Portfolio'),
        ),
        migrations.AlterField(
            model_name='screenshotsportfolio',
            name='screen_shot',
            field=models.ImageField(upload_to=cv.models.ScreenShotsPortfolio.rename_upload_screen_shot, verbose_name='Capture'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Decription'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('main', 'Principal'), ('about', 'A propos'), ('facts', 'Faits'), ('skills', 'Compétences'), ('resume', 'Curuculum Vitae'), ('portfolio', 'Portfolio'), ('certificats', 'Certificats'), ('testimonials', 'Témoignages'), ('contact', 'Nous Contacter')], max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='section',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.userprofile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(blank=True, default=80, null=True, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.userprofile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Quote'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default_avatar.jpg', upload_to=cv.models.UserProfile.rename_upload_avatar, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bg_wallpaper',
            field=models.ImageField(blank=True, default='bg_wallpaper/default_bg.jpg', null=True, upload_to=cv.models.UserProfile.rename_upload_bg_wallpaper, verbose_name='Bannière'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=cv.models.UserProfile.rename_upload_file, verbose_name='Fichier CV'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Diplôme'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[cv.models.validate_facebook_profile], verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Femelle', 'Femelle'), ('Male', 'Male')], default='Male', max_length=10, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[cv.models.validate_github_profile], verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[cv.models.validate_instagram_profile], verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[cv.models.validate_linkedin_profile], verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[cv.models.validate_twitter_profile], verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='works',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.resume', verbose_name='Entrée CV'),
        ),
        migrations.AlterField(
            model_name='works',
            name='work',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Travail'),
        ),
    ]
