# Generated by Django 4.1.3 on 2022-12-25 06:00

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_fact_iconeb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default_avatar.jpg', height_field=600, max_length=600, upload_to=cv.models.UserProfile.rename_upload_avatar, verbose_name='Avatar', width_field=600),
        ),
    ]
