# Generated by Django 4.1.3 on 2022-12-25 06:02

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default_avatar.jpg', upload_to=cv.models.UserProfile.rename_upload_avatar, verbose_name='Avatar'),
        ),
    ]
