# Generated by Django 4.1.3 on 2022-12-25 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesportfolio',
            options={'verbose_name': 'Catégorie de Portfolio', 'verbose_name_plural': '08.Catégories de Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificat', 'verbose_name_plural': '11.Certificats'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['timestamp'], 'verbose_name': 'Contacte', 'verbose_name_plural': '13.Contactes'},
        ),
        migrations.AlterModelOptions(
            name='fact',
            options={'ordering': ['name'], 'verbose_name': 'Fait', 'verbose_name_plural': '04.Faits'},
        ),
        migrations.AlterModelOptions(
            name='i_am',
            options={'verbose_name': 'Portrait', 'verbose_name_plural': '03.Portraits '},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name'], 'verbose_name': 'Portfolio', 'verbose_name_plural': '09.Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['title'], 'verbose_name': 'CV', 'verbose_name_plural': '06.CVs'},
        ),
        migrations.AlterModelOptions(
            name='screenshotsportfolio',
            options={'verbose_name': 'Capture de Portfolio', 'verbose_name_plural': '10.Captures de Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': '01.Sections'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Compétence', 'verbose_name_plural': '05.Compétences'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['name'], 'verbose_name': 'Témoignage', 'verbose_name_plural': '12.Témoignages'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profile utilisateur', 'verbose_name_plural': '02.Profiles utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'ordering': ['work'], 'verbose_name': 'Travail', 'verbose_name_plural': '07.Travaux'},
        ),
        migrations.AddField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cv.userprofile'),
            preserve_default=False,
        ),
    ]
